# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FolderList.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 328)
        self.GroupProjectFolders = QtWidgets.QGroupBox(Form)
        self.GroupProjectFolders.setGeometry(QtCore.QRect(80, 70, 261, 151))
        self.GroupProjectFolders.setObjectName("GroupProjectFolders")
        self.FolderList = QtWidgets.QListWidget(self.GroupProjectFolders)
        self.FolderList.setGeometry(QtCore.QRect(10, 20, 241, 81))
        self.FolderList.setObjectName("FolderList")
        self.ButtonAddFolder = QtWidgets.QPushButton(self.GroupProjectFolders)
        self.ButtonAddFolder.setGeometry(QtCore.QRect(120, 110, 121, 31))
        self.ButtonAddFolder.setObjectName("ButtonAddFolder")
        self.ButtonRemoveFolder = QtWidgets.QPushButton(self.GroupProjectFolders)
        self.ButtonRemoveFolder.setGeometry(QtCore.QRect(18, 110, 91, 31))
        self.ButtonRemoveFolder.setObjectName("ButtonRemoveFolder")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.GroupProjectFolders.setTitle(_translate("Form", "Folder List"))
        self.ButtonAddFolder.setText(_translate("Form", "Remove Folder"))
        self.ButtonRemoveFolder.setText(_translate("Form", "Add Folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
