# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RootWidget(object):
    def setupUi(self, RootWidget):
        RootWidget.setObjectName("RootWidget")
        RootWidget.resize(974, 277)
        self.RootWidgetLayout = QtWidgets.QGridLayout(RootWidget)
        self.RootWidgetLayout.setObjectName("RootWidgetLayout")
        self.projectsContents = QtWidgets.QFrame(RootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectsContents.sizePolicy().hasHeightForWidth())
        self.projectsContents.setSizePolicy(sizePolicy)
        self.projectsContents.setMinimumSize(QtCore.QSize(0, 120))
        self.projectsContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectsContents.setFrameShape(QtWidgets.QFrame.Box)
        self.projectsContents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projectsContents.setObjectName("projectsContents")
        self.projectsContentsLayout = QtWidgets.QGridLayout(self.projectsContents)
        self.projectsContentsLayout.setObjectName("projectsContentsLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.projectsContentsLayout.addItem(spacerItem, 0, 1, 2, 1)
        self.description = QtWidgets.QLabel(self.projectsContents)
        self.description.setObjectName("description")
        self.projectsContentsLayout.addWidget(self.description, 1, 3, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.projectsContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(100, 0))
        self.openButton.setObjectName("openButton")
        self.projectsContentsLayout.addWidget(self.openButton, 0, 4, 2, 1)
        self.icon = QtWidgets.QLabel(self.projectsContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMaximumSize(QtCore.QSize(100, 100))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/images/Images/UnityIcon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.projectsContentsLayout.addWidget(self.icon, 0, 0, 2, 1)
        self.title = QtWidgets.QLabel(self.projectsContents)
        self.title.setObjectName("title")
        self.projectsContentsLayout.addWidget(self.title, 0, 3, 1, 1)
        self.RootWidgetLayout.addWidget(self.projectsContents, 0, 0, 1, 1)

        self.retranslateUi(RootWidget)
        QtCore.QMetaObject.connectSlotsByName(RootWidget)

    def retranslateUi(self, RootWidget):
        _translate = QtCore.QCoreApplication.translate
        RootWidget.setWindowTitle(_translate("RootWidget", "Form"))
        self.description.setText(_translate("RootWidget", "desc"))
        self.openButton.setText(_translate("RootWidget", "Open"))
        self.title.setText(_translate("RootWidget", "title"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RootWidget = QtWidgets.QWidget()
    ui = Ui_RootWidget()
    ui.setupUi(RootWidget)
    RootWidget.show()
    sys.exit(app.exec_())
