# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UnityLauncher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 470)
        MainWindow.setStyleSheet("*\n"
"{\n"
"    background-color: rgb(26, 26, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(38, 38, 38);\n"
"}\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    color: rgb(152, 153, 153);\n"
"    background-color: rgb(38, 38, 38);\n"
"    border: 1px solid rgb(48, 48, 48);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background: rgb(38, 38, 38);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidgetLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralwidgetLayout.setObjectName("centralwidgetLayout")
        self.openButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.openButton_5.setObjectName("openButton_5")
        self.centralwidgetLayout.addWidget(self.openButton_5, 2, 1, 1, 1)
        self.newProjectButton = QtWidgets.QPushButton(self.centralwidget)
        self.newProjectButton.setObjectName("newProjectButton")
        self.centralwidgetLayout.addWidget(self.newProjectButton, 2, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.centralwidgetLayout.addWidget(self.titleLabel, 2, 0, 1, 1)
        self.projectsScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.projectsScrollArea.setWidgetResizable(True)
        self.projectsScrollArea.setObjectName("projectsScrollArea")
        self.projectsContents = QtWidgets.QWidget()
        self.projectsContents.setGeometry(QtCore.QRect(0, 0, 688, 374))
        self.projectsContents.setObjectName("projectsContents")
        self.projectsContentsLayout = QtWidgets.QVBoxLayout(self.projectsContents)
        self.projectsContentsLayout.setObjectName("projectsContentsLayout")
        self.sortButtons = QtWidgets.QWidget(self.projectsContents)
        self.sortButtons.setObjectName("sortButtons")
        self.sortButtonsLayout = QtWidgets.QGridLayout(self.sortButtons)
        self.sortButtonsLayout.setObjectName("sortButtonsLayout")
        self.pushButton = QtWidgets.QPushButton(self.sortButtons)
        self.pushButton.setStyleSheet("color: rgb(152, 153, 153);\n"
"background-color: rgb(38, 38, 38);\n"
"border: 1px solid rgb(48, 48, 48);")
        self.pushButton.setObjectName("pushButton")
        self.sortButtonsLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.sortButtons)
        self.pushButton_3.setStyleSheet("color: rgb(152, 153, 153);\n"
"background-color: rgb(38, 38, 38);\n"
"border: 1px solid rgb(48, 48, 48);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.sortButtonsLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.sortButtons)
        self.pushButton_2.setStyleSheet("color: rgb(152, 153, 153);\n"
"background-color: rgb(38, 38, 38);\n"
"border: 1px solid rgb(48, 48, 48);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.sortButtonsLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.projectsContentsLayout.addWidget(self.sortButtons)
        self.projectsScrollArea.setWidget(self.projectsContents)
        self.centralwidgetLayout.addWidget(self.projectsScrollArea, 4, 0, 1, 3)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testButton.sizePolicy().hasHeightForWidth())
        self.testButton.setSizePolicy(sizePolicy)
        self.testButton.setMinimumSize(QtCore.QSize(150, 0))
        self.testButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.testButton.setObjectName("testButton")
        self.centralwidgetLayout.addWidget(self.testButton, 3, 0, 1, 1)
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.centralwidgetLayout.addWidget(self.searchLineEdit, 3, 1, 1, 2)
        self.centralwidgetLayout.setColumnStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Unity Launcher"))
        self.openButton_5.setText(_translate("MainWindow", "Open"))
        self.newProjectButton.setText(_translate("MainWindow", "New Project"))
        self.titleLabel.setText(_translate("MainWindow", "Projects"))
        self.pushButton.setText(_translate("MainWindow", "NAME"))
        self.pushButton_3.setText(_translate("MainWindow", "EDITOR VERSION"))
        self.pushButton_2.setText(_translate("MainWindow", "MODIFIED"))
        self.testButton.setText(_translate("MainWindow", "Test Button"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
