# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UnityLauncher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/UnityIconBlack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*\n"
"{\n"
"    background-color: rgb(26, 26, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(38, 38, 38);\n"
"}\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    color: rgb(152, 153, 153);\n"
"    background-color: rgb(38, 38, 38);\n"
"    border: 1px solid rgb(48, 48, 48);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background: rgb(38, 38, 38);\n"
"}\n"
"\n"
"QHeaderView::up-arrow\n"
"{\n"
"    image: url(Images/UpWhiteArrow.png);\n"
"}\n"
"\n"
"QHeaderView::down-arrow\n"
"{\n"
"    image: url(Images/DownWhiteArrow.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidgetLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralwidgetLayout.setObjectName("centralwidgetLayout")
        self.openButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.openButton_5.setObjectName("openButton_5")
        self.centralwidgetLayout.addWidget(self.openButton_5, 2, 1, 1, 1)
        self.newProjectButton = QtWidgets.QPushButton(self.centralwidget)
        self.newProjectButton.setObjectName("newProjectButton")
        self.centralwidgetLayout.addWidget(self.newProjectButton, 2, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.centralwidgetLayout.addWidget(self.titleLabel, 2, 0, 1, 1)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testButton.sizePolicy().hasHeightForWidth())
        self.testButton.setSizePolicy(sizePolicy)
        self.testButton.setMinimumSize(QtCore.QSize(150, 0))
        self.testButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.testButton.setObjectName("testButton")
        self.centralwidgetLayout.addWidget(self.testButton, 3, 0, 1, 1)
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.centralwidgetLayout.addWidget(self.searchLineEdit, 3, 1, 1, 2)
        self.projectTree = QtWidgets.QTreeWidget(self.centralwidget)
        self.projectTree.setIndentation(0)
        self.projectTree.setItemsExpandable(False)
        self.projectTree.setWordWrap(True)
        self.projectTree.setExpandsOnDoubleClick(False)
        self.projectTree.setObjectName("projectTree")
        self.centralwidgetLayout.addWidget(self.projectTree, 4, 0, 1, 3)
        self.centralwidgetLayout.setColumnStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Unity Launcher"))
        self.openButton_5.setText(_translate("MainWindow", "Open"))
        self.newProjectButton.setText(_translate("MainWindow", "New Project"))
        self.titleLabel.setText(_translate("MainWindow", "Projects"))
        self.testButton.setText(_translate("MainWindow", "Test Button"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.projectTree.setSortingEnabled(True)
        self.projectTree.headerItem().setText(0, _translate("MainWindow", "ICON"))
        self.projectTree.headerItem().setText(1, _translate("MainWindow", "NAME"))
        self.projectTree.headerItem().setText(2, _translate("MainWindow", "DESCRIPTION"))
        self.projectTree.headerItem().setText(3, _translate("MainWindow", "MODIFIED"))
        self.projectTree.headerItem().setText(4, _translate("MainWindow", "EDITOR VERSION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
